packages/klevu-core/tsconfig-cjs.json
packages/klevu-core/tsconfig.json

Required to fix support for Adobe PWA studio

Reduce target JS version for CJS version

---

README.md
examples/vue/src/views/Product.vue

Readme for the project has been updated (Work-in-progress)
I also forgot to add the recommendations click event to the Vue example, so it has been added.

Updated readme

---

.vscode/tasks.json
examples/react/src/routes/CategoryPage.tsx
examples/vue/package-lock.json
package-lock.json
packages/klevu-core/README.md
packages/klevu-core/src/connection/klevuFetch.ts
packages/klevu-core/src/models/KlevuFetchResponse.ts
packages/klevu-core/src/queries/search/search.test.ts

Refactor and move next function to lower in hierarchy

---

examples/react/src/routes/SearchResultPage.tsx

Fix demo search landing page

---

examples/react/src/cartContext.tsx
examples/react/src/components/product.tsx
examples/react/src/routes/CategoryPage.tsx
examples/react/src/routes/CheckoutPage.tsx
packages/klevu-core/package-lock.json
packages/klevu-core/package.json
packages/klevu-core/src/connection/klevuFetch.ts
packages/klevu-core/src/events/FetchResultEvents.ts
packages/klevu-core/src/events/KlevuEvents.ts
packages/klevu-core/src/events/eventRequests.ts
packages/klevu-core/src/models/KlevuFetchResponse.ts
packages/klevu-core/src/modifiers/abTest/abTest.ts
packages/klevu-core/src/modifiers/personalisation/personalisation.ts
packages/klevu-core/src/modifiers/sendMerchandisingViewEvent/sendMerchandisingViewEvent.ts
packages/klevu-core/src/modifiers/sendRecommendationViewEvent/sendRecommendationViewEvent.ts
packages/klevu-core/src/modifiers/sendSearchEvent/sendSearchEvent.ts
packages/klevu-core/src/queries/index.ts

A/B testing modifier wasn't sending correct XHR request to Klevu for  A/B testing usage. This fixes it.

Implement missing ab testing calls

---

examples/react/src/routes/CategoryPage.tsx

Clear filters when category page change.

---

packages/klevu-core/src/connection/klevuFetch.ts

Fix next page loading for last page

---

examples/react/README.md
examples/vue/README.md
examples/vue/src/views/Collection.vue
examples/vue/src/views/Home.vue
examples/vue/src/views/Search.vue

Updated docs to callout not using analytics in Quick Search. I also updated the Load More code for the Vue example.

Updated docs + fixed Load More in Vue example

---

examples/hydrogen/hydrogen.config.ts
examples/hydrogen/src/App.server.tsx
examples/hydrogen/src/components/klevu/init.ts
examples/hydrogen/src/components/klevu/utils.ts
examples/hydrogen/src/routes/index.server.tsx

Move from Klevu QA to dedicated Hydrogen example store

Update hydrogen example credentials

---

packages/klevu-core/package.json
packages/klevu-core/src/config.ts
packages/klevu-core/src/modifiers/listFilters/listFilters.ts
packages/klevu-core/src/modifiers/sendRecommendationViewEvent/sendRecommendationViewEvent.ts

* Fixed broken util import (issues #99 and #100) 
* Force run quality of code script on tests to catch these in future

Fix all lint errors and util import bug

---

examples/react/index.html
examples/react/package-lock.json
examples/react/src/index.tsx

React example was not building due to wrong kind of CSS import.

Fix react example build

---

packages/klevu-core/src/store/filterManager.test.ts
packages/klevu-core/src/store/filterManager.ts

Implements and closes #110
Includes tests for FilterManager in same commit
Release tasks:

Creates method to clear Filter Manager selections

---

packages/klevu-core/src/events/FetchResultEvents.test.ts
packages/klevu-core/src/modifiers/applyFilterWithManager/applyFilterWithManager.test.ts
packages/klevu-core/src/modifiers/boostWithFilterManager/boostWithFilterManager.test.ts
packages/klevu-core/src/modifiers/boostWithFilters/boostWithFilters.test.ts
packages/klevu-core/src/modifiers/exclude/exclude.test.ts
packages/klevu-core/src/modifiers/sendRecommendationViewEvent/sendRecommendationViewEvent.test.ts
packages/klevu-core/src/queries/recentlyViewedProducts/recentlyViewedProducts.test.ts
packages/klevu-core/src/queries/recentlyViewedProducts/recentlyViewedProducts.ts
packages/klevu-core/src/queries/similarProducts/similarProducts.ts
packages/klevu-core/src/queries/trendingCategoryProducts/trendingCategoryProducts.test.ts
packages/klevu-core/src/queries/trendingCategoryProducts/trendingCategoryProducts.ts
packages/klevu-core/src/store/klevuFetchCache.test.ts
packages/klevu-core/src/store/klevuFetchCache.ts
packages/klevu-core/src/store/lastClickedProducts.test.ts
packages/klevu-core/src/store/lastSearches.test.ts
packages/klevu-core/src/store/lastSearches.ts

Improve testing of @klevu/core package. Adding more tests to various functions and functionalities.

Add more tests to @klevu/core

---

packages/klevu-core/src/events/KlevuEvents.ts
packages/klevu-core/src/store/lastClickedProducts.ts

Changed typings in events so that KlevuRecord might be missing any keys (as it's possible to select keys in request). 
This leads to better code as it requires checking all API required keys. Which change was done also.
This should fix issue #103

Imporove typings of events

---

packages/klevu-core/src/connection/klevuFetch.ts
packages/klevu-core/src/events/FetchResultEvents.test.ts
packages/klevu-core/src/events/FetchResultEvents.ts
packages/klevu-core/src/events/KlevuEvents.ts
packages/klevu-core/src/events/eventRequests.ts
packages/klevu-core/src/models/KlevuResultEvent.ts

Implements and close #129
Adds ability to override any analytical data in KlevuEvent's class or in `clickSendEvent*` helper functions.

Ability to override any keys in analytical requests

---

examples/react/src/components/appbar.tsx
examples/react/src/components/recommendationBanner.tsx
examples/react/src/routes/ProductPage.tsx
packages/klevu-core/src/config.ts
packages/klevu-core/src/events/eventRequests.ts
packages/klevu-core/src/store/filterManager.test.ts

This automatically saves requests to localStorage for later loading in case that page is changed an analytical request hasn't got time to run.
Closes #116

Implementation of pending analytical requests

---

packages/klevu-core/package-lock.json
packages/klevu-core/package.json
packages/klevu-core/src/models/KlevuListFilter.ts
packages/klevu-core/src/models/KlevuRecordFields.ts
packages/klevu-core/src/models/KlevuTypeOfRecord.ts
packages/klevu-core/src/modifiers/index.ts
packages/klevu-core/src/modifiers/listFilters/listFilters.ts
packages/klevu-core/src/utils/literalUnion.ts
packages/klevu-core/src/utils/valuOf.ts

Copied one used function from type-fest to project in order remove only dependency.

Remove typefest as dependency

---

package-lock.json
package.json
packages/klevu-core/package-lock.json
packages/klevu-core/package.json
packages/klevu-core/src/config.ts
packages/klevu-core/src/connection/fetch.ts
packages/klevu-core/src/connection/klevuFetch.ts
packages/klevu-core/src/connection/resultHelpers/FetchResultEvents.test.ts
packages/klevu-core/src/store/klevuFetchCache.test.ts
packages/klevu-core/src/store/klevuFetchCache.ts

- Fixes bug #142 
- No more local variable cache for other than 200 response coded responses

Fix problem that errors were cached

---

packages/klevu-core/src/modifiers/fallback/fallback.test.ts
packages/klevu-core/src/modifiers/fallback/fallback.ts

Give options parameter for fallback query.

Add options for fallback. Fixes #128

---

packages/klevu-core/src/store/filterManager.test.ts
packages/klevu-core/src/store/filterManager.ts

Simple state saving functions for FilterManager
closes #115

Create manager save/restore state system

---

.github/workflows/release-core.yml
utils/release-klevu-core.js

Haven't been tested as it requires a real release. Waiting for that.

ci/cd for releasing @klevu/core

---

packages/klevu-ui/.storybook/preview-head.html
packages/klevu-ui/src/components/klevu-init/klevu-init.tsx

Reduce size from 3600kb to 296kb

Optimize Google Font download

---

packages/klevu-core/src/store/filterManager.test.ts
packages/klevu-core/src/store/filterManager.ts

Fix bug with reading URL params

---

packages/klevu-core/src/queries/kmcRecommendation/kmcRecommendation.ts

Do not require itemGroupId for kmcRecommendations

---

packages/klevu-core/src/models/KlevuApiRawResponse.ts
packages/klevu-core/src/store/filterManager.test.ts
packages/klevu-core/src/store/filterManager.ts

Creates new feature to filter manager that lists all currently selected filters as simple array.
Implements and closes #267

Add selected filters feature to FilterManager

---

packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-button/klevu-button.tsx
packages/klevu-ui/src/components/klevu-button/readme.md
packages/klevu-ui/src/components/klevu-chat-bubble/klevu-chat-bubble.css
packages/klevu-ui/src/components/klevu-chat-bubble/klevu-chat-bubble.tsx
packages/klevu-ui/src/components/klevu-chat-messages/klevu-chat-messages.css
packages/klevu-ui/src/components/klevu-chat-messages/readme.md
packages/klevu-ui/src/components/klevu-loading-indicator/readme.md
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.css
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-product-query/readme.md
packages/klevu-ui/src/global/global.css
packages/klevu-ui/src/utils/utils.ts

Small improvements for PQA application

Improvements to PQA

---

packages/klevu-core/src/connection/moi/moi.ts
packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/package.json
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-product-query/readme.md

Adds support to fetch PQA context by productId and not just by the URL.

Add PQA productId support

---

packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-chat-messages/readme.md
packages/klevu-ui/src/components/klevu-modal/readme.md
packages/klevu-ui/src/components/klevu-popup/klevu-popup.css
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/components/klevu-popup/readme.md
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.css
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.mdx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-product-query/readme.md

Updates to PQA application by request.

PQA updates by request

---

packages/klevu-ui/.storybook/main.js
packages/klevu-ui/.storybook/preview-body.html
packages/klevu-ui/.storybook/preview-head.html
packages/klevu-ui/package-lock.json
packages/klevu-ui/package.json
packages/klevu-ui/src/components/klevu-init/klevu-init.tsx
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/storybookUtils.ts
packages/klevu-ui/src/utils/utils.ts
packages/klevu-ui/storybookAddons/constants.ts
packages/klevu-ui/storybookAddons/klevuSettings.tsx
packages/klevu-ui/storybookAddons/preview.ts
packages/klevu-ui/storybookAddons/register.ts

New button to Storybook that allows users set api-key and url to their liking.

Storybook settings system

---

packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.css
packages/klevu-ui/src/components/klevu-chat-messages/readme.md
packages/klevu-ui/src/components/klevu-popup/klevu-popup.css
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.css
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.css
packages/klevu-ui/src/components/klevu-typography/klevu-typography.css

* Prevent popup from managing content height. Let is always be what requested. 
* When small enough screen size force a fixed container for popup content

Change popup functionality to not change height of content

---

packages/klevu-ui/package-lock.json
packages/klevu-ui/package.json
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.tsx
packages/klevu-ui/src/components/klevu-query/klevu-query.tsx
packages/klevu-ui/src/components/klevu-search-field/klevu-search-field.tsx
packages/klevu-ui/src/components/klevu-search-field/readme.md
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx

Updates @klevu/core package to 3.0.0 in @klevu/ui

Update core to 3.0.0 in UI

---

packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-button/klevu-button.css
packages/klevu-ui/src/components/klevu-chat-bubble/readme.md
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.css
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.stories.ts
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.tsx
packages/klevu-ui/src/components/klevu-chat-layout/readme.md
packages/klevu-ui/src/components/klevu-chat-messages/klevu-chat-messages.css
packages/klevu-ui/src/components/klevu-chat-messages/klevu-chat-messages.stories.ts
packages/klevu-ui/src/components/klevu-chat-messages/klevu-chat-messages.tsx
packages/klevu-ui/src/components/klevu-chat-messages/readme.md
packages/klevu-ui/src/components/klevu-moi/klevu-moi.css
packages/klevu-ui/src/components/klevu-moi/klevu-moi.stories.ts
packages/klevu-ui/src/components/klevu-moi/klevu-moi.tsx
packages/klevu-ui/src/components/klevu-moi/readme.md
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.css
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-product/klevu-product.tsx
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx
packages/klevu-ui/src/components/klevu-quicksearch/readme.md
packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.tsx
packages/klevu-ui/src/components/klevu-search-field/klevu-search-field.tsx
packages/klevu-ui/src/components/klevu-slides/readme.md
packages/klevu-ui/src/components/klevu-typography/readme.md
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.css
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.tsx

Fix UI layouting for MOI and PQA

Fix bugs from Moi and PQA

---

packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx

Fixed popup width not working in desktop version.

Fix popup bug that came from last bug fix

---

packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.css
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.tsx
packages/klevu-ui/src/components/klevu-chat-layout/readme.md
packages/klevu-ui/src/components/klevu-chat-messages/readme.md
packages/klevu-ui/src/components/klevu-moi/klevu-moi.css
packages/klevu-ui/src/components/klevu-moi/klevu-moi.stories.ts
packages/klevu-ui/src/components/klevu-moi/klevu-moi.tsx
packages/klevu-ui/src/components/klevu-moi/readme.md
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.css
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-product-query/readme.md
packages/klevu-ui/src/components/klevu-quicksearch/readme.md
packages/klevu-ui/src/components/klevu-typography/readme.md
packages/klevu-ui/src/components/klevu-util-scrollbars/readme.md

Making them use same components and calculations.

Fix Moi and PQA responsive

---

packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx

If pqaWidgetId is set check that service can be enabled.

PQA checks that can be started

---

packages/klevu-ui/package-lock.json
packages/klevu-ui/package.json
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.css
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.tsx
packages/klevu-ui/src/components/klevu-chat-layout/readme.md
packages/klevu-ui/src/components/klevu-chat-messages/readme.md
packages/klevu-ui/src/components/klevu-moi/klevu-moi.tsx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.css
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.css
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.mdx
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.stories.ts
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.tsx

* scrollbars solution was fixed with CSS, removed custom calculation
* Added missing klevu specific scrollbar styles that were lost on update
* Update @klevu/core to 3.0.1

Revert scrollbar changes to CSS based solution

---

packages/klevu-core/src/connection/moi/moi.ts

Add possibility to add klevuSettings to MOI/PQA interface.

Add settings parameter to MoiRequest

---

packages/klevu-core/src/connection/moi/moi.ts
packages/klevu-ui/package.json

MOI didn't save it's session after first request. Now save the state after every initialization.

Save MOI session on init already

---

packages/klevu-ui/src/components/klevu-popup/klevu-popup.css
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts

- Calculate popup size just when showing the popup to fix sizing
- Set the popup z-index to prevent it going under other elements

Fix klevu-popup sizing and z-index

---

examples/react-klevu-ui-v2/src/HomePage.tsx

@nikhil-narayana-klevu: Now it works 😄

Fix toggling of values in ui react example

---

packages/klevu-ui/src/components/klevu-popup/klevu-popup.css

This code prevents overriding position of popup from fixed to absolute

UI: Fix popups inside popups

---

packages/klevu-core/src/events/KlevuEvents.ts

Add More specific types for KlevuEvents so that it's clear what is required.
And fix bug about using wrong price value in recommendation events.

CORE: More specific types for KlevuEvents

---

packages/klevu-ui/package-lock.json
packages/klevu-ui/src/components/klevu-recommendations/Custom Recommendation.mdx
packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.stories.ts
packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.tsx

And created a customized recommendation example.

UI: Fix scrolling of recommendation products

---

packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/package-lock.json
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.stories.ts
packages/klevu-ui/src/components/klevu-chat-layout/klevu-chat-layout.tsx
packages/klevu-ui/src/components/klevu-product-query-popup/klevu-product-query-popup.css
packages/klevu-ui/src/components/klevu-product-query-popup/klevu-product-query-popup.tsx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-slides/klevu-slides.tsx
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.css
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.stories.ts
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.tsx
packages/klevu-ui/src/utils/utils.ts

And force text-align left for chat.

UI: Give abitility to choose native scrollbars

---

packages/klevu-ui/src/components/klevu-slider/klevu-slider.tsx

Solution from this page
https://refreshless.com/nouislider/examples/#section-merging-tooltips

UI: Prevent slider tooltips from overlapping

---

packages/klevu-ui/src/components/klevu-init/klevu-init.stories.ts
packages/klevu-ui/src/components/klevu-query/klevu-query.stories.ts
packages/klevu-ui/src/components/klevu-util-portal/klevu-util-portal.stories.ts
packages/klevu-ui/src/components/klevu-util-scrollbars/klevu-util-scrollbars.stories.ts
packages/klevu-ui/src/stories/installation.mdx
packages/klevu-ui/src/stories/styles.mdx
packages/klevu-ui/src/stories/usage.mdx

Some spelling changes
Added default output to the Non-components section instead of seeing empty page.
Renamed the utils components
Removed a section we discussed to be removed.

Docs: Improvements to stories

---

packages/klevu-ui/src/components/klevu-chat-bubble/klevu-chat-bubble.stories.ts

"Fixes" the problem with feedback icons by changing the the example

Docs: Update chat bubble story to be more realistic

---

packages/klevu-ui/.storybook/blocks/KlevuAutoDocs.jsx
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-merchandising/CustomContent.mdx
packages/klevu-ui/src/components/klevu-merchandising/Stylished.mdx
packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.mdx
packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.stories.ts
packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.tsx
packages/klevu-ui/src/components/klevu-product/klevu-product.tsx
packages/klevu-ui/src/components/klevu-quicksearch/Stylished.mdx
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.stories.ts
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx
packages/klevu-ui/src/components/klevu-recommendations/Stylished.mdx
packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.stories.ts
packages/klevu-ui/src/components/klevu-search-landing-page/Stylished.mdx
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.stories.ts
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx
packages/klevu-ui/src/components/klevu-slides/klevu-slides.tsx
packages/klevu-ui/src/components/klevu-typography/klevu-typography.css

- Created documentation and parts selectors for applications
- Organized files a bit
- Update KlevuAutoDocs and KlevuCSSEditor

UI: CSS parts for application components

---

packages/klevu-core/src/connection/responseQueryObject.ts
packages/klevu-core/src/events/KlevuEvents.ts

THIS IS A BACKWARDS COMPABILITY BREAKING CHANGE!
To conform same structure as other KlevuEvent functions.

CORE: Destructure merchandising product click - BREAKING

---

examples/react/package-lock.json
examples/react/src/routes/CheckoutPage.tsx
packages/klevu-core/src/events/KlevuEvents.ts
packages/klevu-core/src/events/eventRequests.ts

- Deprecate old way of providing checkout data
- Use new one in KlevuEvents buy()

CORE: New buy() and checkout events

---

packages/klevu-core/package.json
packages/klevu-core/src/connection/fetch.ts
packages/klevu-core/src/version.ts
packages/klevu-core/version.js

Adds current version of klevu core as `x-klevu-core` header

CORE: Add current version as headers when making requests

---

packages/klevu-core/package.json
packages/klevu-core/src/connection/fetch.ts
packages/klevu-core/src/version.ts
packages/klevu-core/version.js

Reverts klevultd/frontend-sdk#457
None of the requests work with custom headers.

Revert "CORE: Add current version as headers when making requests"

---

packages/klevu-ui/src/components/klevu-facet/klevu-facet.tsx
packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.stories.ts

Moving the slot assignment to the span fixes issue.

Fixing the slot assignment

---

packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-popup/klevu-popup.css
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/components/klevu-product-query-popup/klevu-product-query-popup.css
packages/klevu-ui/src/components/klevu-product-query-popup/klevu-product-query-popup.tsx
packages/klevu-ui/src/components/klevu-product-query/Heavity modified version.mdx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.mdx
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts
packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.tsx
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.css
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.css
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx

Also improve the documentation explaining the nuances of styling product query application.

UI: Add ability to change size of the popup in PQA

---

packages/klevu-core/src/modifiers/abTest/abTest.ts

CORE: Update URL for ab testing

---

packages/klevu-ui/src/components/klevu-checkbox/klevu-checkbox.css
packages/klevu-ui/src/components/klevu-dropdown/klevu-dropdown.css

* fixed when dropdown caused a layout shift when getting active state
* fixed checkbox active state border being 1px too wide and high

UI: Dropdown layoutshift and checkbox focus size fix

---

packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx

klevu-popup toggle didn't work. It opened popup right after closing it.

UI: Fix popup toggle not working

---

packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-popup/klevu-popup.css
packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx
packages/klevu-ui/src/components/klevu-search-field/klevu-search-field.tsx

* Add ability for popup to define origin to fill the space.
* Make option for quicksearch that hides button in default mode

UI: Quicksearch improvements

---

packages/klevu-core/src/queries/kmcRecommendation/kmcRecommendation.ts
packages/klevu-ui-vue/src/components.ts
packages/klevu-ui/src/components.d.ts
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.stories.ts
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx
packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.stories.ts
packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.tsx
packages/klevu-ui/src/components/klevu-search-field/klevu-search-field.tsx
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.stories.ts
packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx

Added props to pass search `options` to
1. Search Landing page
2. Recommendations
3. QuickSearch

[UI] Added code to support options in app components

---

packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.css
packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx

Show popular searches when no results found.

[UI] - Adds popular searches when no results found

---

examples/react/package-lock.json
examples/react/package.json
packages/klevu-core/src/events/eventRequests.ts

We also changed the @klevu/core reference in the package.json file for the react demo from a version to the local repo. This is necessary for local testing.

change buy event from beacon to post to fix formdata compatibility issue
