packages/klevu-core/src/connection/fetch.ts, packages/klevu-core/src/connection/klevuFetch.ts, packages/klevu-core/src/events/eventRequests.ts, packages/klevu-core/src/queries/kmcRecommendation/kmcRecommendation.ts, packages/klevu-core/tsconfig-base.json
When analytical calls was returning xml fetch was trying to read it as json.
Now result can be ignored from request.
=> Fix fetch error logs

packages/klevu-core/src/store/klevuFetchCache.ts
Traditional reference problem. Fixed by saving cache as string and converting it back.
This closes #65
=> Fix cache problem

packages/klevu-core/src/utils/cleanSearchQuery.ts
Only security issue in the project is the unsafe strip tags code. Remove it as it is not used in anywhere.
=> Remove unsafe strip tags function

examples/react/src/routes/CategoryPage.tsx
Add support for Category Merchandizing Campaigns in the React demo
the parameter is "campaignId". 
For example: http://localhost:3001/category/Men?campaignId=3 or http://localhost:3001/category/Women?campaignId=3 will give one version of the category, but omitting the parameter will result in the normal result set for the category.
=> Add campaignId support in React demo

packages/klevu-core/src/connection/klevuFetch.ts, packages/klevu-core/src/connection/resultHelpers/fetchNextPage.test.ts, packages/klevu-core/src/connection/resultHelpers/fetchNextPage.ts, packages/klevu-core/src/models/KlevuFetchResponse.ts
Implements new `getPage()` helper. It's same as `next()`, but it returns even though on the last page.
`getPage()` works exactly the same as `next()` without parameters. Due to that I have set `next()` deprecated function.
Biggest change is that both deprecated `next()` and `getPage()` has new parameter `pageIndex`. This allows to request certain page instead of next one. Not providing this pageIndex will automatically go to next page.
=> Implement getPage helper. Closes #161

packages/klevu-core/src/connection/klevuFetch.test.ts, packages/klevu-core/src/connection/resultHelpers/FetchResultEvents.test.ts, packages/klevu-core/src/queries/kmcRecommendation/kmcRecommendation.test.ts
Skip recommendation tests as the account where it was tested doesn't exists anymore.
And created new generic tests for `KlevuFetch()`
=> Fix tests and create new one

packages/klevu-core/src/modifiers/listFilters/listFilters.test.ts, packages/klevu-core/src/store/filterManager.test.ts, packages/klevu-core/src/store/filterManager.ts
This PR changes totally the way FilterManager works in the SDK. This is breaking change to the logic of the FilterManager.
Now instead of separate `options` and `sliders` there is just single `filters` array that contains both. There is a new feature in Klevu Merchant Center that allows reordering facets. With previous solution it was impossible to change the order sliders and options.
Options and sliders and still supported by this change, but they are marked as deprecated.
Two new features were added:
1) Ability to create URL parameters from FilterManager
2) Ability to set filters based on URL parameters
=> Filter Manager refactor

packages/klevu-core/src/modifiers/sendMerchandisingViewEvent/sendMerchandisingViewEvent.ts, packages/klevu-core/src/modifiers/sendRecommendationViewEvent/sendRecommendationViewEvent.ts, packages/klevu-core/src/modifiers/sendSearchEvent/sendSearchEvent.ts, packages/klevu-core/src/modifiers/sendSearchEvent/sendSearchEvents.test.ts
Add override parameter to `sendSearchEvent()`, `sendRecommendationViewEvent()` and `sendMerchandisingViewEvent()` functions.
=> Add possibility to override analytical requests parameter on modifiers

packages/klevu-core/src/queries/kmcRecommendation/kmcRecommendation.ts
Splitting out VisuallySimilar recs logic into it's own block because it uses sourceObjects, but the other recommendation types still use recentObjects.
=> sourceObjects vs recentObjects fix for recs

packages/klevu-core/src/queries/newarrivals/newarrivals.ts
New arrivals was displaying new CMS's and categories. Now it displays only new products.
=> Limit new arrival products to only product types

packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx
When displaying popup on small screen make it overlay whole screen from top left instead of origin.
=> Popup fullscreen on mobile

packages/klevu-ui/src/components/klevu-product/klevu-product.css, packages/klevu-ui/src/components/klevu-product/klevu-product.stories.ts, packages/klevu-ui/src/components/klevu-product/klevu-product.tsx
when there is no image available in `klevu-product` it shows a `klevu-icon` placeholder for missing image.
=> Add no image placeholder for the klevu-product

examples/vanillajs/index.html, examples/vanillajs/package-lock.json, examples/vanillajs/recommendationskmc.html, examples/vanillajs/recommendationskmc.ts, packages/klevu-core/src/connection/responseObject.ts, packages/klevu-core/src/connection/responseQueryObject.ts
Now function parameters can be fetched from query results with `query.getQueryParameters()` method.
=> Improve query object to fetch query params more cleaner way

packages/klevu-ui/src/components/klevu-popup/klevu-popup.css, packages/klevu-ui/src/components/klevu-popup/klevu-popup.tsx, packages/klevu-ui/src/components/klevu-product-query/Heavity modified version.mdx, packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.mdx, packages/klevu-ui/src/components/klevu-product-query/klevu-product-query.stories.ts
Fix popups being in container instead of dialog element itself. 
This allows dialog backdrops to function correctly.
=> UI: Move klevu-popup to fully use dialog instead of container

packages/klevu-core/src/connection/kmc.ts, packages/klevu-core/src/connection/kmcmodels/KMCMaps.ts, packages/klevu-core/src/connection/responseQueryObject.ts, packages/klevu-core/src/connection/resultHelpers/getRedirects.test.ts, packages/klevu-core/src/connection/resultHelpers/getRedirects.ts
- Adds a helper function feature to search results which can be used to fetch redirects that match the search
- Adds configuration for KMCSetting so that caching length can be adjusted from 24 hours.
=> CORE: Add helper for getting redirects and configurable cache length

packages/klevu-core/src/config.ts, packages/klevu-core/src/store/lastClickedProducts.test.ts, packages/klevu-core/src/store/lastClickedProducts.ts
For GDPR reasons it sometimes it is required to disable all kind of tracking even in the memory level.
=> CORE: Add parameter to config init to prevent click tracking

packages/klevu-ui/.gitignore, packages/klevu-ui/package.json, packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.tsx, packages/klevu-ui/src/components/klevu-recommendations/klevu-recommendations.tsx, packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx, packages/klevu-ui/src/stories/hydration.mdx, packages/klevu-ui/stencil.config.ts
Gives components ability to hydrate components on server side.
To use: 
```
import { renderToString } from "@klevu/ui/hydrate";
const result = await renderToString("<klevu-button>Hello world</klevu-button>");
result.html // contains HTML content of hydration
```
=> UI: Add ability to hydrate Klevu Components

packages/klevu-ui/src/components/klevu-product/klevu-product.tsx
When fallback image wasn't defined for product it was causing a request to `/undefined`
=> UI: Fixed undefined fallback causing request

examples/vanillajs-klevu-ui/index.html, examples/vanillajs-klevu-ui/package-lock.json, packages/klevu-core/src/store/filterManager.test.ts, packages/klevu-core/src/store/filterManager.ts, packages/klevu-ui-vue/src/components.ts, packages/klevu-ui/package-lock.json, packages/klevu-ui/package.json, packages/klevu-ui/src/components.d.ts, packages/klevu-ui/src/components/klevu-facet-list/klevu-facet-list.tsx, packages/klevu-ui/src/components/klevu-facet/klevu-facet.tsx, packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.stories.ts, packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.tsx, packages/klevu-ui/src/components/klevu-pagination/klevu-pagination.tsx, packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx
Here is change suggestions to PR #535
* It reduces complexity of handing URL parameters by not using `encodeURI` and  `decodeURI` in any place.
* Adds tests
* Fixes storybook stories
* Changes vanillaJS example to use it
* Removes extra logic from `klevu-facet` 
* Removes checking if `window.history` exists. It's already very old tech and doesn't need extra checks.
=> Change suggestions for PR #535

examples/vanillajs-klevu-ui/index.html, examples/vanillajs-klevu-ui/package-lock.json, packages/klevu-core/docs/modules.md, packages/klevu-core/src/store/filterManager.test.ts, packages/klevu-core/src/store/filterManager.ts, packages/klevu-ui-vue/src/components.ts, packages/klevu-ui/package-lock.json, packages/klevu-ui/package.json, packages/klevu-ui/src/components.d.ts, packages/klevu-ui/src/components/klevu-facet-list/klevu-facet-list.tsx, packages/klevu-ui/src/components/klevu-facet/klevu-facet.tsx, packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.stories.ts, packages/klevu-ui/src/components/klevu-merchandising/klevu-merchandising.tsx, packages/klevu-ui/src/components/klevu-pagination/klevu-pagination.tsx, packages/klevu-ui/src/components/klevu-quicksearch/klevu-quicksearch.tsx, packages/klevu-ui/src/components/klevu-search-landing-page/klevu-search-landing-page.tsx
[CORE]
Added optional parameter to the `searchParams` to the `toUrlParams` function to allow initial value for conversion.
[UI]
Added support to allow saving facet selections and page numbers in url.
Added new attribute `autoUpdateUrl` to the klevu-merchandising and klevu-search-landing-page components to enable feature.
Added attributes to klevu-pagination and klevu-facet-list to enable feature at the component level.
=> CORE & UI: Add support for adding Facets and Pagination to URL

packages/klevu-core/src/modifiers/personalisation/personalisation.ts, packages/klevu-core/src/store/lastClickedProducts.test.ts, packages/klevu-core/src/store/lastClickedProducts.ts
When using `personalisation` modifer we remove the duplicate ids from requests so that we can get more products to affect the personalisation.
=> CORE: Remove duplicate ids from personalisation requests
